"""
SSH CA setup scripts — Unix shell variants + dispatcher.
"""

from .setup_scripts_win import _user_ca_script_windows, _host_ca_script_windows


def _generate_setup_script(ca, pub_key, ca_type, hostname, platform='unix'):
    """Build a shell or PowerShell script for SSH CA trust configuration."""
    ca_label = ca.descr.replace("'", "'\\''")

    if platform == 'windows':
        # PowerShell escaping: backtick-escape backticks, escape single quotes for here-strings
        ps_key = pub_key.strip().replace('\n', ' ').replace('`', '``')
        ps_label = ca.descr.replace('`', '``').replace('"', '`"')
        if ca_type == 'user':
            return _user_ca_script_windows(ps_key, ps_label)
        return _host_ca_script_windows(ps_key, ps_label, hostname)

    safe_key = pub_key.strip().replace("\n", " ").replace("'", "'\\''")
    if ca_type == 'user':
        return _user_ca_script(safe_key, ca_label)
    return _host_ca_script(safe_key, ca_label, hostname)


def _user_ca_script(pub_key, ca_label):
    return rf'''#!/bin/sh
# ============================================================================
# SSH User CA Trust Setup Script
# CA: {ca_label}
# Generated by UCM (Ultimate Certificate Manager)
#
# This script configures sshd to trust certificates signed by the above CA
# for user authentication (TrustedUserCAKeys).
#
# Usage:
#   sudo sh setup_script.sh              # Apply changes
#   sudo sh setup_script.sh --dry-run    # Preview without modifying
# ============================================================================

set -eu

# --- Configuration ---
CA_KEY_DIR="/etc/ssh/ssh_ca_keys"
CA_KEY_FILE="$CA_KEY_DIR/user_ca.pub"
SSHD_CONFIG="/etc/ssh/sshd_config"
PRINCIPALS_DIR="/etc/ssh/auth_principals"
DRY_RUN=false

# --- Colors ---
if [ -t 1 ]; then
    RED="\\033[0;31m"
    GREEN="\\033[0;32m"
    YELLOW="\\033[0;33m"
    BLUE="\\033[0;34m"
    BOLD="\\033[1m"
    NC="\\033[0m"
else
    RED="" GREEN="" YELLOW="" BLUE="" BOLD="" NC=""
fi

# --- Helpers ---
info()  {{ printf "%b[INFO]%b  %s\\n" "$BLUE" "$NC" "$1"; }}
ok()    {{ printf "%b[OK]%b    %s\\n" "$GREEN" "$NC" "$1"; }}
warn()  {{ printf "%b[WARN]%b  %s\\n" "$YELLOW" "$NC" "$1"; }}
err()   {{ printf "%b[ERROR]%b %s\\n" "$RED" "$NC" "$1" >&2; }}

# --- Parse arguments ---
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --help|-h)
            printf "Usage: sudo sh %s [--dry-run]\\n" "$0"
            printf "  --dry-run  Show what would be changed without modifying anything\\n"
            exit 0
            ;;
        *) err "Unknown option: $arg"; exit 1 ;;
    esac
done

# --- Root check ---
if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (or with sudo)."
    exit 1
fi

printf "%b========================================%b\\n" "$BOLD" "$NC"
printf "%bSSH User CA Trust Setup%b\\n" "$BOLD" "$NC"
printf "CA: %s\\n" "{ca_label}"
if [ "$DRY_RUN" = true ]; then
    printf "%b>>> DRY RUN — no changes will be made <<<%b\\n" "$YELLOW" "$NC"
fi
printf "%b========================================%b\\n\\n" "$BOLD" "$NC"

# --- Detect OS ---
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_ID="$ID"
    OS_NAME="$PRETTY_NAME"
else
    OS_ID="unknown"
    OS_NAME="Unknown OS"
fi
info "Detected OS: $OS_NAME"

# --- Determine sshd restart command ---
detect_restart_cmd() {{
    if command -v systemctl >/dev/null 2>&1; then
        if systemctl list-unit-files sshd.service >/dev/null 2>&1; then
            echo "systemctl reload sshd"
        else
            echo "systemctl reload ssh"
        fi
    elif command -v rc-service >/dev/null 2>&1; then
        echo "rc-service sshd reload"
    elif command -v service >/dev/null 2>&1; then
        echo "service sshd reload"
    else
        echo ""
    fi
}}

RESTART_CMD=$(detect_restart_cmd)
if [ -z "$RESTART_CMD" ]; then
    warn "Could not detect sshd service manager. You will need to reload sshd manually."
fi

# --- Step 1: Create CA key directory ---
info "Creating CA key directory: $CA_KEY_DIR"
if [ "$DRY_RUN" = true ]; then
    if [ -d "$CA_KEY_DIR" ]; then
        ok "Directory already exists (no change needed)"
    else
        info "Would create: $CA_KEY_DIR"
    fi
else
    mkdir -p "$CA_KEY_DIR"
    chmod 755 "$CA_KEY_DIR"
    ok "Directory ready: $CA_KEY_DIR"
fi

# --- Step 2: Write CA public key ---
CA_PUB_KEY='{pub_key}'

info "Writing CA public key to: $CA_KEY_FILE"
if [ "$DRY_RUN" = true ]; then
    if [ -f "$CA_KEY_FILE" ]; then
        EXISTING=$(cat "$CA_KEY_FILE" 2>/dev/null || echo "")
        if [ "$EXISTING" = "$CA_PUB_KEY" ]; then
            ok "Key file already contains the correct key (no change needed)"
        else
            warn "Would overwrite existing key file"
        fi
    else
        info "Would create: $CA_KEY_FILE"
    fi
else
    printf "%s\\n" "$CA_PUB_KEY" > "$CA_KEY_FILE"
    chmod 644 "$CA_KEY_FILE"
    ok "CA public key written"
fi

# --- Step 3: Back up sshd_config ---
if [ ! -f "$SSHD_CONFIG" ]; then
    err "sshd_config not found at $SSHD_CONFIG"
    exit 1
fi

BACKUP="$SSHD_CONFIG.bak.$(date +%Y%m%d%H%M%S)"
info "Backing up sshd_config to: $BACKUP"
if [ "$DRY_RUN" = true ]; then
    info "Would create backup: $BACKUP"
else
    cp "$SSHD_CONFIG" "$BACKUP"
    ok "Backup created"
fi

# --- Step 4: Add TrustedUserCAKeys directive ---
info "Checking sshd_config for TrustedUserCAKeys directive..."
if grep -qE "^\\s*TrustedUserCAKeys" "$SSHD_CONFIG" 2>/dev/null; then
    CURRENT=$(grep -E "^\\s*TrustedUserCAKeys" "$SSHD_CONFIG" | head -1)
    warn "TrustedUserCAKeys is already configured: $CURRENT"
    warn "Skipping — please verify the path is correct or update manually."
else
    if [ "$DRY_RUN" = true ]; then
        info "Would add to $SSHD_CONFIG:"
        info "  TrustedUserCAKeys $CA_KEY_FILE"
    else
        printf "\\n# SSH User CA Trust — added by UCM setup script\\nTrustedUserCAKeys %s\\n" "$CA_KEY_FILE" >> "$SSHD_CONFIG"
        ok "Added TrustedUserCAKeys directive to sshd_config"
    fi
fi

# --- Step 5: Set up AuthorizedPrincipalsFile (optional) ---
info "Setting up AuthorizedPrincipalsFile directory: $PRINCIPALS_DIR"
if [ "$DRY_RUN" = true ]; then
    if [ -d "$PRINCIPALS_DIR" ]; then
        ok "Principals directory already exists"
    else
        info "Would create: $PRINCIPALS_DIR"
    fi
else
    mkdir -p "$PRINCIPALS_DIR"
    chmod 755 "$PRINCIPALS_DIR"
    ok "Principals directory ready"
fi

if grep -qE "^\\s*AuthorizedPrincipalsFile" "$SSHD_CONFIG" 2>/dev/null; then
    CURRENT=$(grep -E "^\\s*AuthorizedPrincipalsFile" "$SSHD_CONFIG" | head -1)
    warn "AuthorizedPrincipalsFile already configured: $CURRENT"
else
    if [ "$DRY_RUN" = true ]; then
        info "Would add to $SSHD_CONFIG:"
        info "  AuthorizedPrincipalsFile $PRINCIPALS_DIR/%u"
    else
        printf "AuthorizedPrincipalsFile %s/%%u\\n" "$PRINCIPALS_DIR" >> "$SSHD_CONFIG"
        ok "Added AuthorizedPrincipalsFile directive"
    fi
fi

# --- Step 6: Validate sshd config ---
info "Validating sshd configuration..."
if command -v sshd >/dev/null 2>&1; then
    if [ "$DRY_RUN" = true ]; then
        info "Would run: sshd -t"
    else
        if sshd -t 2>/dev/null; then
            ok "sshd configuration is valid"
        else
            err "sshd configuration test failed! Restoring backup..."
            cp "$BACKUP" "$SSHD_CONFIG"
            err "Backup restored. Please check your sshd_config manually."
            exit 1
        fi
    fi
else
    warn "sshd binary not found in PATH — skipping config validation"
fi

# --- Step 7: Reload sshd ---
if [ -n "$RESTART_CMD" ]; then
    info "Reloading sshd: $RESTART_CMD"
    if [ "$DRY_RUN" = true ]; then
        info "Would run: $RESTART_CMD"
    else
        if $RESTART_CMD; then
            ok "sshd reloaded successfully"
        else
            warn "sshd reload returned non-zero. Check service status manually."
        fi
    fi
fi

# --- Done ---
printf "\\n%b========================================%b\\n" "$BOLD" "$NC"
if [ "$DRY_RUN" = true ]; then
    printf "%bDry run complete — no changes were made.%b\\n" "$YELLOW" "$NC"
else
    printf "%bSetup complete!%b\\n" "$GREEN" "$NC"
fi
printf "%b========================================%b\\n\\n" "$BOLD" "$NC"

if [ "$DRY_RUN" != true ]; then
    info "Next steps:"
    info "  1. For each user, create a principals file:"
    info "     echo \\"principal_name\\" > $PRINCIPALS_DIR/<username>"
    info "  2. Sign user keys with the CA using UCM or ssh-keygen"
    info "  3. Users can now log in with their signed certificate"
fi
'''


def _host_ca_script(pub_key, ca_label, hostname):
    hostname_display = hostname if hostname else '$(hostname -f)'
    return rf'''#!/bin/sh
# ============================================================================
# SSH Host CA Trust Setup Script
# CA: {ca_label}
# Generated by UCM (Ultimate Certificate Manager)
#
# This script configures sshd to present a host certificate signed by the
# above CA, proving the server\'s identity to connecting clients.
#
# Usage:
#   sudo sh setup_script.sh              # Apply changes
#   sudo sh setup_script.sh --dry-run    # Preview without modifying
# ============================================================================

set -eu

# --- Configuration ---
CA_KEY_DIR="/etc/ssh/ssh_ca_keys"
CA_KEY_FILE="$CA_KEY_DIR/host_ca.pub"
SSHD_CONFIG="/etc/ssh/sshd_config"
HOSTNAME="{hostname if hostname else ""}"
DRY_RUN=false

# --- Colors ---
if [ -t 1 ]; then
    RED="\\033[0;31m"
    GREEN="\\033[0;32m"
    YELLOW="\\033[0;33m"
    BLUE="\\033[0;34m"
    BOLD="\\033[1m"
    NC="\\033[0m"
else
    RED="" GREEN="" YELLOW="" BLUE="" BOLD="" NC=""
fi

# --- Helpers ---
info()  {{ printf "%b[INFO]%b  %s\\n" "$BLUE" "$NC" "$1"; }}
ok()    {{ printf "%b[OK]%b    %s\\n" "$GREEN" "$NC" "$1"; }}
warn()  {{ printf "%b[WARN]%b  %s\\n" "$YELLOW" "$NC" "$1"; }}
err()   {{ printf "%b[ERROR]%b %s\\n" "$RED" "$NC" "$1" >&2; }}

# --- Parse arguments ---
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --help|-h)
            printf "Usage: sudo sh %s [--dry-run]\\n" "$0"
            printf "  --dry-run  Show what would be changed without modifying anything\\n"
            exit 0
            ;;
        *) err "Unknown option: $arg"; exit 1 ;;
    esac
done

# --- Root check ---
if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (or with sudo)."
    exit 1
fi

# --- Resolve hostname ---
if [ -z "$HOSTNAME" ]; then
    HOSTNAME=$(hostname -f 2>/dev/null || hostname)
fi

printf "%b========================================%b\\n" "$BOLD" "$NC"
printf "%bSSH Host CA Trust Setup%b\\n" "$BOLD" "$NC"
printf "CA: %s\\n" "{ca_label}"
printf "Host: %s\\n" "$HOSTNAME"
if [ "$DRY_RUN" = true ]; then
    printf "%b>>> DRY RUN — no changes will be made <<<%b\\n" "$YELLOW" "$NC"
fi
printf "%b========================================%b\\n\\n" "$BOLD" "$NC"

# --- Detect OS ---
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_ID="$ID"
    OS_NAME="$PRETTY_NAME"
else
    OS_ID="unknown"
    OS_NAME="Unknown OS"
fi
info "Detected OS: $OS_NAME"

# --- Determine sshd restart command ---
detect_restart_cmd() {{
    if command -v systemctl >/dev/null 2>&1; then
        if systemctl list-unit-files sshd.service >/dev/null 2>&1; then
            echo "systemctl reload sshd"
        else
            echo "systemctl reload ssh"
        fi
    elif command -v rc-service >/dev/null 2>&1; then
        echo "rc-service sshd reload"
    elif command -v service >/dev/null 2>&1; then
        echo "service sshd reload"
    else
        echo ""
    fi
}}

RESTART_CMD=$(detect_restart_cmd)
if [ -z "$RESTART_CMD" ]; then
    warn "Could not detect sshd service manager. You will need to reload sshd manually."
fi

# --- Step 1: Create CA key directory ---
info "Creating CA key directory: $CA_KEY_DIR"
if [ "$DRY_RUN" = true ]; then
    if [ -d "$CA_KEY_DIR" ]; then
        ok "Directory already exists (no change needed)"
    else
        info "Would create: $CA_KEY_DIR"
    fi
else
    mkdir -p "$CA_KEY_DIR"
    chmod 755 "$CA_KEY_DIR"
    ok "Directory ready: $CA_KEY_DIR"
fi

# --- Step 2: Write CA public key ---
CA_PUB_KEY='{pub_key}'

info "Writing CA public key to: $CA_KEY_FILE"
if [ "$DRY_RUN" = true ]; then
    if [ -f "$CA_KEY_FILE" ]; then
        EXISTING=$(cat "$CA_KEY_FILE" 2>/dev/null || echo "")
        if [ "$EXISTING" = "$CA_PUB_KEY" ]; then
            ok "Key file already contains the correct key (no change needed)"
        else
            warn "Would overwrite existing key file"
        fi
    else
        info "Would create: $CA_KEY_FILE"
    fi
else
    printf "%s\\n" "$CA_PUB_KEY" > "$CA_KEY_FILE"
    chmod 644 "$CA_KEY_FILE"
    ok "CA public key written"
fi

# --- Step 3: Back up sshd_config ---
if [ ! -f "$SSHD_CONFIG" ]; then
    err "sshd_config not found at $SSHD_CONFIG"
    exit 1
fi

BACKUP="$SSHD_CONFIG.bak.$(date +%Y%m%d%H%M%S)"
info "Backing up sshd_config to: $BACKUP"
if [ "$DRY_RUN" = true ]; then
    info "Would create backup: $BACKUP"
else
    cp "$SSHD_CONFIG" "$BACKUP"
    ok "Backup created"
fi

# --- Step 4: Sign the host key ---
# Find available host keys
HOST_KEY=""
for kt in ed25519 ecdsa rsa; do
    if [ -f "/etc/ssh/ssh_host_${{kt}}_key.pub" ]; then
        HOST_KEY="/etc/ssh/ssh_host_${{kt}}_key"
        break
    fi
done

if [ -z "$HOST_KEY" ]; then
    err "No SSH host key found in /etc/ssh/"
    exit 1
fi

CERT_FILE="${{HOST_KEY}}-cert.pub"
info "Found host key: $HOST_KEY"

if [ -f "$CERT_FILE" ]; then
    warn "Host certificate already exists: $CERT_FILE"
    warn "If you want to re-sign, remove it first and re-run this script."
else
    printf "\\n"
    warn "Host key signing requires the CA private key, which is managed by UCM."
    info "To sign the host key, use one of these methods:"
    printf "\\n"
    info "  Option A: Sign via UCM web interface"
    info "    1. Copy the host public key: $HOST_KEY.pub"
    info "    2. Go to UCM > SSH > Certificates > Sign Host Key"
    info "    3. Upload the public key and specify principals: $HOSTNAME"
    info "    4. Download the signed certificate"
    info "    5. Place it at: $CERT_FILE"
    printf "\\n"
    info "  Option B: Sign via UCM API"
    info "    curl -X POST https://<ucm-server>/api/v2/ssh/certificates/sign \\\\"
    info "      -H 'Content-Type: application/json' \\\\"
    info "      -d '{{\"ca_id\": {ca_label}, \"cert_type\": \"host\", ...}}'"
    printf "\\n"
fi

# --- Step 5: Add HostCertificate directive ---
info "Checking sshd_config for HostCertificate directive..."
if grep -qE "^\\s*HostCertificate" "$SSHD_CONFIG" 2>/dev/null; then
    CURRENT=$(grep -E "^\\s*HostCertificate" "$SSHD_CONFIG" | head -1)
    warn "HostCertificate is already configured: $CURRENT"
    warn "Skipping — please verify the path is correct or update manually."
else
    if [ "$DRY_RUN" = true ]; then
        info "Would add to $SSHD_CONFIG:"
        info "  HostCertificate $CERT_FILE"
    else
        printf "\\n# SSH Host Certificate — added by UCM setup script\\nHostCertificate %s\\n" "$CERT_FILE" >> "$SSHD_CONFIG"
        ok "Added HostCertificate directive to sshd_config"
    fi
fi

# --- Step 6: Validate sshd config ---
info "Validating sshd configuration..."
if command -v sshd >/dev/null 2>&1; then
    if [ "$DRY_RUN" = true ]; then
        info "Would run: sshd -t"
    else
        if sshd -t 2>/dev/null; then
            ok "sshd configuration is valid"
        else
            err "sshd configuration test failed! Restoring backup..."
            cp "$BACKUP" "$SSHD_CONFIG"
            err "Backup restored. Please check your sshd_config manually."
            exit 1
        fi
    fi
else
    warn "sshd binary not found in PATH — skipping config validation"
fi

# --- Step 7: Reload sshd ---
if [ -n "$RESTART_CMD" ]; then
    info "Reloading sshd: $RESTART_CMD"
    if [ "$DRY_RUN" = true ]; then
        info "Would run: $RESTART_CMD"
    else
        if [ -f "$CERT_FILE" ]; then
            if $RESTART_CMD; then
                ok "sshd reloaded successfully"
            else
                warn "sshd reload returned non-zero. Check service status manually."
            fi
        else
            warn "Skipping sshd reload — host certificate not yet present."
            warn "Sign the host key first, then reload sshd manually."
        fi
    fi
fi

# --- Done ---
printf "\\n%b========================================%b\\n" "$BOLD" "$NC"
if [ "$DRY_RUN" = true ]; then
    printf "%bDry run complete — no changes were made.%b\\n" "$YELLOW" "$NC"
else
    printf "%bSetup complete!%b\\n" "$GREEN" "$NC"
fi
printf "%b========================================%b\\n\\n" "$BOLD" "$NC"

if [ "$DRY_RUN" != true ]; then
    info "Next steps:"
    if [ ! -f "$CERT_FILE" ]; then
        info "  1. Sign the host key via UCM (see instructions above)"
        info "  2. Place the signed certificate at: $CERT_FILE"
        info "  3. Reload sshd: $RESTART_CMD"
    fi
    info "  Clients should add to their ~/.ssh/known_hosts or ssh_known_hosts:"
    info "    @cert-authority * $(cat $CA_KEY_FILE 2>/dev/null || echo '<CA public key>')"
fi
'''
